######################################################################
# Automatically generated by qmake (3.0) ?? 4? 26 17:26:21 2024
######################################################################

TEMPLATE = app
TARGET = qmake
INCLUDEPATH += .

# Input
SOURCES += qmake.cpp

QT += widgets gui
